### ISSUE TITLE
Time calculating program

### ISSUE THREAD

**Issue by Nish251103** [devptyagi/AutomatedAttendance-OpenCV-Python#1]
It would be a python program which would store the time at which the user has joined and has been marked their attendance.
 kindly assign me the task/issue for the same.

Regards
Nishchal

**Comment by devptyagi** [comment]
That's amazing! All the best ✌🏻

**Comment by Nish251103** [comment]
Thank You. I will start my work on it ASAP

**Comment by Nish251103** [comment]
Work done
